# This file was generated by GoReleaser. DO NOT EDIT.
cask "axx" do
  version "0.1.8"

  on_macos do
    on_arm do
      sha256 "5ac1a26895894580b9a332e53c4abec681061233afa1558eac24f2846e9f4688"
      url "https://github.com/nimbusxr/axx/releases/download/v#{version}/axx_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9edd2d5727d7a3edbb3da1609e2a2a9f9dd103d6b60a3a330c5f5f957e4747dd"
      url "https://github.com/nimbusxr/axx/releases/download/v#{version}/axx_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "164a378fb5c79b11c9e5197a8ca6b8d2a0a2b3feaf03d4c279f7d756ad600867"
      url "https://github.com/nimbusxr/axx/releases/download/v#{version}/axx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2837aae4af7621902d2bbfc99dccbdc37338199447b00fca3699e28d7aa47095"
      url "https://github.com/nimbusxr/axx/releases/download/v#{version}/axx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "axx"
  desc "Human-readable acceptance testing for the agentic era"
  homepage "https://axx.nimbusxr.us"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "axx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/axx"]
    end
  end

  # No zap stanza required
end
