# This file was generated by GoReleaser. DO NOT EDIT.
cask "axx" do
  version "0.2.9"

  on_macos do
    on_arm do
      sha256 "2794725c1b04e2ea6b202525e8b596226423816231715425470773de68bc102e"
      url "https://github.com/nimbusxr/axx/releases/download/v#{version}/axx_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2d2eb9f605aa6682bd68cedb36cf9bccf7fa0c92c46732bd98a895c165d96ef6"
      url "https://github.com/nimbusxr/axx/releases/download/v#{version}/axx_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d90571086666190f48e648e0330166af54e77aa838d6b026d050d40d8a94874e"
      url "https://github.com/nimbusxr/axx/releases/download/v#{version}/axx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8cef9f10b24de3b015e318fc8e3753d0bf030fa6383a0d06a3757e60a8c32889"
      url "https://github.com/nimbusxr/axx/releases/download/v#{version}/axx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "axx"
  desc "Human-readable acceptance testing for the agentic era"
  homepage "https://axx.nimbusxr.us"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "axx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/axx"]
    end
  end

  # No zap stanza required
end
