# This file was generated by GoReleaser. DO NOT EDIT.
cask "axx" do
  version "0.1.10"

  on_macos do
    on_arm do
      sha256 "af6804197efc98369fd339da53860c25e118855bba1110be696b9ab659605e8a"
      url "https://github.com/nimbusxr/axx/releases/download/v#{version}/axx_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7b44692a4ee62f5ab883387f6061f64565e14aa61f1122771ef8d9de49bb3133"
      url "https://github.com/nimbusxr/axx/releases/download/v#{version}/axx_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c00947463ca718151322003dce926a34b571de54f2c7ac8080dc8f07d76a2690"
      url "https://github.com/nimbusxr/axx/releases/download/v#{version}/axx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d52fc7e30fa2bff8fc5ce966cc721de2da84049565d613ccf79fa22368ad3620"
      url "https://github.com/nimbusxr/axx/releases/download/v#{version}/axx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "axx"
  desc "Human-readable acceptance testing for the agentic era"
  homepage "https://axx.nimbusxr.us"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "axx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/axx"]
    end
  end

  # No zap stanza required
end
